server:
  port: 8810

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
    #注意：这里要在hosts文件里面编写配置映射  后面需要配置eureka集群以及路由，索性一次性配置完成
    #127.0.0.1       eureka7001.com
  #127.0.0.1       eureka7002.com
  #127.0.0.1       eureka7003.com
  #127.0.0.1       zuul5555.com
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。暴露给服务的注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
