server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yangjie.springcloud.yangjiecloudapi.entity    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml                    # mapper映射文件

spring:
  application:
    #特别重要！！对外暴露的微服务名字
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/yangjie              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#  instance:
#    instance-id: microservicecloud-dept8001 #自定义服务名称信息
#    prefer-ip-address: true     #访问路径可以显示IP地址
#
#当在eureka里面点击服务名字时，返回json而不是404
#info:
#  app.name: atguigu-microservicecloud
#  company.name: www.atguigu.com
#
#  #可能是我父pom里面的插件配置的有问题，以下两个变量的值我没取到
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$


